import Head from "next/head";
import Image from "next/image";
import Link from "next/link";
import axios from "axios";
import { useEffect, useState } from "react";
// css
import styles from "../styles/Home.module.css";
// layout
import MainLayout from "../layouts/MainLayout";
// swiper
import { Swiper, SwiperSlide } from "swiper/react";
import { FreeMode } from "swiper";
import "swiper/css";
import "swiper/css/free-mode";

export default function Home() {
  const [data, setData] = useState([]);
  const [search, setSearch] = useState({ title: "" });
  useEffect(() => {
    axios.get("/api/recipe/").then((res) => setData(res.data));
  }, []);

  const handleSubmit = (event) => {
    event.preventDefault();
  };

  return (
    <div className={styles.content}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {/* content */}
      <main className="container">
        <MainLayout>
          {/* input search */}
          <form onSubmit={handleSubmit}>
            <div className="input-group mt-4">
              <input
                type="text"
                className="form-control py-2 ps-4 ms-2"
                placeholder="Search Pasta, Bread, etc"
                aria-label="Recipient's username"
                aria-describedby="button-addon2"
                value={search.title}
                onChange={(event) => setSearch({ title: event.target.value })}
              />
              <Link href={{ pathname: "/searchPage", query: search }}>
                <button
                  className="btn btn-warning text-white px-4 me-2"
                  type="submit"
                >
                  <i className="bi bi-search"></i>
                </button>
              </Link>
            </div>
          </form>
          {/* End input search */}

          {/* Populer for you */}
          <section>
            <h3 className="mt-4 mx-3">Populer For You</h3>
            <div className="row mt-4 mx-2">
              {[
                {
                  name: "Soup",
                  image: "/images/group-icon-1.png",
                  link: "/populer/soup",
                },
                {
                  name: "Chicken",
                  image: "/images/group-icon-2.png",
                  link: "/populer/chicken",
                },
                {
                  name: "Dessert",
                  image: "/images/group-icon-3.png",
                  link: "/populer/dessert",
                },
                {
                  name: "Seafood",
                  image: "/images/group-icon-2.png",
                  link: "/populer/seafood",
                },
              ].map((item, index) => (
                <div className="col-3" key={index}>
                  <Image
                    src={item?.image}
                    alt="logo"
                    width="70px"
                    height="70px"
                  />
                  <p className="text-center text-muted">{item?.name}</p>
                </div>
              ))}
            </div>
          </section>
          {/* End Populer for you */}

          {/* New recipe */}
          <section>
            <h3 className="m-3">New Recipe</h3>
            <div className="d-flex justify-content-center mx-3">
              <Swiper
                freeMode={true}
                grabCursor={true}
                modules={[FreeMode]}
                className="mySwiper"
                slidesPerView={2}
                // spaceBetween={30}
              >
                {data.map((item) => (
                  <SwiperSlide key={item?.id_recipe}>
                    <Link href={"/detailRecipe/" + item?.id_recipe}>
                      <div className={`card ${styles.caraousel}`}>
                        <Image
                          src={item?.photo}
                          alt="logo"
                          width="100%"
                          height="160%"
                        />
                      </div>
                    </Link>
                  </SwiperSlide>
                ))}
              </Swiper>
            </div>
          </section>
          {/* End New recipe */}

          {/* Populer recipe */}
          <section>
            <h3 className="mb-3 mt-5 mx-3">Populer recipe</h3>
            <div className="d-flex align-items-center flex-column px-3">
              {data.map((item) => (
                <div
                  key={item?.id_recipe}
                  className={`card shadow mx-3 mb-3 ${styles.card_img}`}
                >
                  <div className="row g-0">
                    <div className="col-4 py-2 ps-2">
                      <Image
                        src={item?.photo}
                        alt="logo"
                        width="100%"
                        height="100%"
                      />
                    </div>
                    <div className="col-8">
                      <div className="card-body">
                        <h5 className="card-title text-secondary">
                          {item?.title_recipe}
                        </h5>
                        <small className="text-muted">Sweet, Gentle</small>
                        <p className="card-text text-warning mt-1">
                          <i className="bi bi-star-fill"></i>
                          <small className="text-muted ms-2">4.7</small>
                        </p>
                      </div>
                    </div>
                  </div>
                </div>
              ))}
            </div>
          </section>
          {/* End Populer recipe */}
        </MainLayout>
      </main>
      {/* End Content */}
    </div>
  );
}
